# 空氣污染監測網 網路爬蟲實作練習


* 能夠利用 selenium + BeautifulSoup 撰寫爬蟲，並存放到合適的資料結構

## 作業目標

根據範例 ，完成以下問題：

* ① 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料
* ② 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料

### ① 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料

In [1]:
# 打開瀏覽器

from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup

browser = webdriver.Chrome(executable_path='chromedriver')

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")

In [3]:
# 模擬使用者操作行為，選擇/點擊

selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('11')
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')

browser.find_element_by_id('ctl05_btnQuery').click()

In [4]:
# 取得資料，丟到 BeautifulSoup 解析

html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tbody><tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>1.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>1.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>3.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>1.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>1.90</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>1.80</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2018/01</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>0.44</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>0.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>0.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>0.21</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>0.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>0.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>0.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>0.35</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>33.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>32.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>38.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>31.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>29.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>18.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>29.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>45.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>32.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>30.70</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2018/01</td><td>23</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>24</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>25</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>21</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>14.17</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>19.43</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>18.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>15.24</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>15.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>13.79</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>11.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>14.75</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>12.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>12.45</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>13.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>14.56</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>3.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>4.48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>4.93</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>2.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.68</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.68</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>2.13</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>2.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>3.42</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>10.77</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>14.95</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>13.56</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>12.64</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>12.94</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>11.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>8.92</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>12.08</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>10.33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>10.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>11.15</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</tbody></table>

In [15]:
d={}
end = 0
for tr in table.find_all('tr')[1:]:
    for i, td in enumerate(tr.find_all('td')):

        if len(tr.find_all('td')) == 5:
            if end >0:
                break
            if i == 0:
                obs = td.text
                d.setdefault(obs, {})
            if i == 2:
                date = td.text
            if i == 3:
                value = td.text
                d[obs][date] = value
                end +=1
        
        if len(tr.find_all('td')) == 3:
            if i == 0:
                date = td.text
            if i == 1:
                value = td.text
                d[obs][date] = value
print(d)

{'SO2': {'2018/01': '1.80', '2018/02': '14.95', '2018/03': '13.56', '2018/04': '12.64', '2018/05': '12.94', '2018/06': '11.38', '2018/07': '8.92', '2018/08': '12.08', '2018/09': '10', '2018/10': '10.33', '2018/11': '10.71', '2018/12': '11.15'}}

In [16]:
import pandas as pd
pd.DataFrame(d)

           SO2
2018/01   1.80
2018/02  14.95
2018/03  13.56
2018/04  12.64
2018/05  12.94
2018/06  11.38
2018/07   8.92
2018/08  12.08
2018/09     10
2018/10  10.33
2018/11  10.71
2018/12  11.15

### ② 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料

In [17]:
# 打開瀏覽器

from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup

browser = webdriver.Chrome(executable_path='chromedriver')

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")

In [18]:
# 模擬使用者操作行為，選擇/點擊

selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('11')
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')

browser.find_element_by_id('ctl05_btnQuery').click()

In [19]:
# 取得資料，丟到 BeautifulSoup 解析

html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tbody><tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>1.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>1.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>3.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>1.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>1.90</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>1.80</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2018/01</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>0.44</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>0.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>0.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>0.21</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>0.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>0.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>0.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>0.35</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>33.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>32.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>38.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>31.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>29.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>18.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>29.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>45.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>32.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>30.70</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2018/01</td><td>23</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>24</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>25</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>21</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>14.17</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>19.43</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>18.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>15.24</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>15.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>13.79</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>11.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>14.75</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>12.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>12.45</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>13.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>14.56</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>3.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>4.48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>4.93</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>2.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.68</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.68</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>2.13</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>2.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>3.42</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>10.77</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>14.95</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>13.56</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>12.64</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>12.94</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>11.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>8.92</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>12.08</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>10.33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>10.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>11.15</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</tbody></table>

In [21]:
d={}
end = 0
for tr in table.find_all('tr')[1:]:
    for i, td in enumerate(tr.find_all('td')):

        if len(tr.find_all('td')) == 5:
            if end >1:
                break
            if i == 0:
                obs = td.text
                d.setdefault(obs, {})
            if i == 2:
                date = td.text
            if i == 3:
                value = td.text
                d[obs][date] = value
                end +=1
        
        if len(tr.find_all('td')) == 3:
            if i == 0:
                date = td.text
            if i == 1:
                value = td.text
                d[obs][date] = value
print(d)

{'SO2': {'2018/01': '1.80', '2018/02': '1.90', '2018/03': '2.20', '2018/04': '2.30', '2018/05': '3.10', '2018/06': '2.70', '2018/07': '2.20', '2018/08': '2.40', '2018/09': '2.10', '2018/10': '1.70', '2018/11': '1.90', '2018/12': '1.80'}, 'CO': {'2018/01': '0.34', '2018/02': '14.95', '2018/03': '13.56', '2018/04': '12.64', '2018/05': '12.94', '2018/06': '11.38', '2018/07': '8.92', '2018/08': '12.08', '2018/09': '10', '2018/10': '10.33', '2018/11': '10.71', '2018/12': '11.15'}}

In [22]:
import pandas as pd
pd.DataFrame(d)

          SO2     CO
2018/01  1.80   0.34
2018/02  1.90  14.95
2018/03  2.20  13.56
2018/04  2.30  12.64
2018/05  3.10  12.94
2018/06  2.70  11.38
2018/07  2.20   8.92
2018/08  2.40  12.08
2018/09  2.10     10
2018/10  1.70  10.33
2018/11  1.90  10.71
2018/12  1.80  11.15